apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-postgres-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-postgres-app
  template:
    metadata:
      labels:
        app: python-postgres-app
    spec:
      containers:
      - name: python-postgres-app
        image: chailearngke/python-postgres-k8s-test:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "my-postgres.cvii02ai6sn1.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: DB_USER
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: DB_PASSWORD
