apiVersion: v1
kind: Service
metadata:
  name: python-postgres-app
spec:
  type: LoadBalancer
  selector:
    app: python-postgres-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
